### ISSUE TITLE
I need your help <3

### ISSUE THREAD

**Issue by Xing-C** [Lanfix8/SimpleHealthBar-Forge#2]
Hello friend, I have made modifications to your code and added new features, just like in the picture,
This is the feature I need, but I want to share this module with more people. What should I do?
I think I need your consent. Should I publish as a new module or?

![T`_QYLYH%QTQW6KG2FKQ{$J](https://github.com/Lanfix8/SimpleHealthBar-Forge/assets/39401415/4eef1c0e-416d-4560-a7a7-481a24f3f559)
![9KVR2%VEFN7UO4YV(NA2UMT](https://github.com/Lanfix8/SimpleHealthBar-Forge/assets/39401415/336af1aa-632c-439d-b425-0bc8c8b012be)

**Comment by Lanfix8** [comment]
Hello !
It looks like you have put in a lot of work !
These images are very interesting, but the goal of my mod was just to display the health in a bar, which is useful when you have more than 20 hp.
If you want to create your own mod like this, there is no problem, it looks way different than mine.
What are the most important features you want to be added ? So maybe I can create a new version that will satisfy you.
Have a great day !

**Comment by Xing-C** [comment]
Yes, your great work is aimed at health status, which is very good. If you are not prepared to display all the information, I think it can currently be in perfect form

> Hello ! It looks like you have put in a lot of work ! These images are very interesting, but the goal of my mod was just to display the health in a bar, which is useful when you have more than 20 hp. If you want to create your own mod like this, there is no problem, it looks way different than mine. What are the most important features you want to be added ? So maybe I can create a new version that will satisfy you. Have a great day !

**Comment by Lanfix8** [comment]
And there is a few mods that display all the information similarly to how you did it (there was none just changing the health bar)
So maybe you can find what you are looking for

**Comment by Xing-C** [comment]
In version 1.20.1, I couldn't find
And I put the source code here: https://github.com/Xing-C/Classic-and-simple-status-bars
> And there is a few mods that display all the information similarly to how you did it (there was none just changing the health bar) So maybe you can find what you are looking for

**Comment by Lanfix8** [comment]
Ok that's fine then, you can publish your mod if you put in the credits that the basis of the code was made by Lanfix or that it is based on SimpleHealthBar (with the link of the page of my mod)

**Comment by Xing-C** [comment]
Thank
